name: ExpertBuild
author: Marodeur
main: fr.Marodeur.ExpertBuild.Main
version: '${version}'
api-version: 1.18
description: Builder plugin
website: https://github.com/LucasT-dev
depend: [ WorldEdit ]

commands:

  expbuild:
    aliases: exp
    description: general command
    permission: expbuild.use

  pos:
    description: get player position
    permission: exppos.use

  vox:
    description: give Voxel tool
    permission: expvox.use

  plume:
    description: give GoPaint tool
    permission: expplume.use

  silex:
    description: give GoBrush tool
    permission: expsilex.use

  terra:
    aliases: t
    descrption: give all tool
    permission: expterra.use

  1:
    description: First position WE
    permission: exptool.use

  2:
    description: Second position WE
    permission: exptool.use

  c:
    aliases: copy
    description: copy WE
    permission: exptool.use

  p:
    description: paste WE
    permission: expp.use

  pa:
    description: paste -a WE
    permission: exppa.use

  poly:
    description: sel poly WE
    permission: exptool.use

  cube:
    description: sel cuboid WE
    permission: exptool.use

  convex:
    aliases: conv
    description: sel convex WE
    permission: exptool.use

  f:
    aliases: flip
    description: rotate
    permission: expf.use

  s:
    description: set
    permission: exps.use

  sel:
    description: sel
    permission: expsel.use

  flower:
    aliases: fw
    decription: brush
    permission: expflower.use

  timelapse:
    description: launch automatic timelapse
    permission: exptimelapse.use

  schemtrans:
    description: transfert schem on other serveur
    permission: expschemtrans.use

  easyplanting:
    aliases: ep
    description: set random clipboard
    permission: expeasyplanting.use

  repeater:
    aliases: rt
    description: preset a tick to the repeater when you set it
    permission: exptool.use

  perlin:
    description: generate perlin
    permission: expperlin.use

  autocb:
    description: automatic set cb with pre save command
    permission: expautocb.use

  getcommand:
    description: displays the command of a Block command by looking at it from a distance
    permission: expgetcommand.use

  autoflip:
    description: Use your selection as a plane of symmetry
    permission: expautoflip.use

  convertslab:
    description: Convert double slab to block
    permission: expconvertslab.use
