name: ExpertBuild
author: Marodeur
main: fr.marodeur.expertbuild.Main
version: '${version}'
api-version: 1.18
description: Builder plugin
website: https://github.com/LucasT-dev
depend: [ WorldEdit ]
libraries:
  - io.github.rysefoxx.inventory:RyseInventory-Plugin:1.5.7

commands:

  expbuild:
    aliases: exp
    description: general command
    permission: exp.command.build

  pos:
    description: get player position
    permission: exp.command.pos

  vox:
    description: give Voxel tool
    permission: exp.command.vox

  plume:
    description: give GoPaint tool
    permission: exp.command.plume

  silex:
    description: give GoBrush tool
    permission: exp.command.silex

  terra:
    aliases: t
    descrption: give all tool
    permission: exp.command.terra

  1:
    description: First position WE
    permission: exp.command.tool

  2:
    description: Second position WE
    permission: exp.command.tool

  c:
    aliases: copy
    description: copy WE
    permission: exp.command.tool

  p:
    description: paste WE
    permission: exp.command.p

  pa:
    description: paste -a WE
    permission: exp.command.pa

  poly:
    description: sel poly WE
    permission: exp.command.tool

  cube:
    description: sel cuboid WE
    permission: exp.command.tool

  convex:
    aliases: conv
    description: sel convex WE
    permission: exp.command.tool

  sel:
    description: sel
    permission: exp.command.sel

  flower:
    aliases: fw
    decription: brush
    permission: exp.command.flower

  slab:
    aliases: bs
    description: casse la dalle
    permission: exp.command.slab

  timelapse:
    description: launch automatic timelapse
    permission: exp.command.timelapse

  schemtrans:
    description: transfert schem on other serveur
    permission: exp.command.schemtrans

  maze:
    description: Generate maze
    permission: exp.command.maze

  repeater:
    aliases: rt
    description: preset a tick to the repeater when you set it
    permission: exp.command.tool

  perlin:
    description: generate perlin
    permission: exp.command.perlin

  autocb:
    description: automatic set cb with pre save command
    permission: exp.command.autocb

  getcommand:
    description: displays the command of a Block command by looking at it from a distance
    permission: exp.command.getcommand

  convertslab:
    description: Convert double slab to block
    permission: exp.command.convertslab

  dungeons:
    description: procedural dungeons
    permission: exp.command.dungeons

  painting:
    description: advanced painting tool
    permission: exp.command.painting

  explsystem:
    description: L system generation
    permission: exp.command.explsystem

  areatimer:
    description: areatimer for timing
    permission: exp.command.areatimer

permissions:

  exp.register:
    default: op

  exp.brush.biome:
    default: op
  exp.brush.blendball:
    default: op
  exp.brush.clipboard3d:
    default: op
  exp.brush.clipboard:
    default: op
  exp.brush.cube:
    default: op
  exp.brush.degrade:
    default: op
  exp.brush.drain:
    default: op
  exp.brush.eraser:
    default: op
  exp.brush.erodeblend:
    default: op
  exp.brush.custom:
    default: op
  exp.brush.erode:
    default: op
  exp.brush.flower:
    default: op
  exp.brush.line:
    default: op
  exp.brush.none:
    default: op
  exp.brush.overlay:
    default: op
  exp.brush.2dcube:
    default: op
  exp.brush.sphere:
    default: op
  exp.brush.spike:
    default: op
  exp.brush.updatechunk:
    default: op

  exp.gui.main:
    default: op
  exp.gui.leather:
    default: op
  exp.gui.orga:
    default: op
  exp.gui.flower:
    default: op

  exp.selection.clearselection:
    default: op
  exp.selection.airpos:
    default: op