# EXP-Build

build:
  # Open or close the schematic transfer
  # Value : Boolean (true or false)
  server_1:
    statserver: false
    name: server_1
  server_2:
    statserver: false
    name: server_2
  server_3:
    statserver: false
    name: server_3
  server_4:
    statserver: false
    name: server_4

  #Max file size to transfer (ko)
  #Default : 500
  #-1 for by-pass
  max_file_size: 500

  #Maximum size brush
  #Default : 50
  #Use integer value
  max_brush_rayon: 50

  #default brush radius
  #Default : 10
  #Use integer value
  default_brush_rayon: 10

  #Default material brush
  #Default : STONE
  #Use block name
  default_material_brush: STONE

  #Default pattern brush
  #Default : 1
  #Id of block
  default_pattern_brush: 1

  #Default biomes brush
  #Default : PLAINS
  #Use Biome name
  default_biome_brush: PLAINS

  #Percentage of air in the flower brush
  #Default : 10
  #Use integer value
  default_air_brush: 10

  #Max distance to apply brush
  #Default : 100
  max_brush_distance: 100

  #Display bezier line on convex selection
  #Default : true
  #Use boolean value (true / false)
  display_bezier_curve: true

  #Player can wand click in air
  #Default : true
  #Use boolean value (true / false)
  wand_click_in_air: true

  #Player can clear selection using shift click with wand
  #Default : false
  #Use boolean value (true / false)
  sihft_click_with_wand: false

  #Max point number save for Brush line
  #Default : 20
  #use integer value
  max_point_saved: 20

  #Terraforming Tool 1
  #Default : ARROW
  #Use item name
  terraforming_tool_1: SPECTRAL_ARROW

  #Terraforming Tool 2
  #Default : GUNPOWDER
  #Use item name
  terraforming_tool_2: CLAY_BALL


  GOHA:
    #Arm length correction factor
    arm_correction_factor: 1.5

    #Material defined by default, modifiable with the command /goha material <block>
    default_material: STONE

    #Default organic height
    default_orga_height: 50

  #lang
  #Default : en (english)
  #possibilité (fr / en )

  lang: en

  message:
    en:
      main:
        plugin_enable: Plugin enable
        plugin_disable: Plugin disable

        listeners_load: Listeners load
        commands_load: Commands load
        config_load: Config load
        gui_load: Gui registered
        brush_load: brush registered
        schematic_transfert_file: Transfert Schematic file Server'num'.yml create

        checking_update: Checking for updates...
        not_new_update: There is not a new update available
        new_update_available: There is a new update available, you are running on version 'v1' , version 'v2' is available
        unable_check_update: Unable to check for updates 'error'

      brush:
        brush_enable: Brush 'brush' enable
        brush_enable_with_radius: Brush 'brush' enable, radius = 'radius'
        brush_enable_with_material: Brush 'brush' enable, pattern = 'pattern'
        brush_enable_with_radius_pattern: Brush 'brush' enable, radius = 'radius', pattern = 'pattern'
        brush_disable: Brush disable
        brush_registered: Brush 'brush' registered
        material_set: Material set
        radius_set: Radius set

        player_registered: Player 'player' registered
        builder_profile_registered: Builder profile registered
        player_already_registered: You have already registered

        point_add: Point add at ('point')
        point_not_save: Limite size, point not save

      permission:
        dont_perm: You don't have the permission
        console_not_execute_cmd: Console cannot use this command

      selection:
        set_pos_1: Pos 1 set to ('pos')
        set_pos_1_with_area: Pos 1 set to ('pos') ('area')
        set_pos_2: Pos 2 set to ('pos')
        set_pos_2_with_area: Pos 2 set to ('pos') ('area')
        add_vertex_pos: Vertex add ('pos')
        selection_clear: Selection clear
        set_selection: Selection 'selection' set

        block_modified: "'num' block have been modified"
        block_modified_with_time: "'num' block have ben modified ('num2' blocks/s)"

      error:
        error_region: Region error n° 'num' ! 'error'
        error_selection: §4Error ! IncompleteRegionException; Use 'selection' selection and complete selection
        error_brushbuilder: §4Error ! 'player' has not been registered as a builder, for this he must be an operator or have the expertbuild.use permission
        error_jsch_exception: Error JSch-Exception, please see console
        error_sftp_exception: Error Sftp-Exception, please see console
        file_configuration_error: Configuration files in ExpertBuild folder is wrong or corrupt; Repair the file or delete all the files, so that the plugin recreates them
        incomplete_selection: Incomplete Selection; Particle Stopped, this is normal
        invalid_number: Invalid number format
        invalid_number_integer: Invalid number format, use integer
        invalid_number_integer_upper_0: Invalid number format, upper 0
        invalid_material: Invalid pattern
        invalid_material_set: Invalid pattern, pattern set 'pattern'
        invalid_biome: Invalid biome
        invalid_biome_set: Invalid biome, biome set 'biome'

      tools:
        give_tool: The 'tool' tools given

      commands:
        use: Use 'cmd'
        pregeneration: Pre-generate
        generate: Generate

        file_not_exist: This file 'file' doesn't exist
        file_too_large: The file is too large, Increase the parameter to transfer larger files
        server_off: Server unregistered
        unknown_server: Unknown server, please try again with valid server name
        transfert: Tranfert running
        dont_restart: Connection to the server... please, don't reload ExpertBuild, don't restart the server
        succes_transfert: Transfer finish, successful upload file Imported-'file' on server 'server'
        transfert_log: The file 'file' Exported with succes by 'player' on 'server'

      gui:
        back: Back
        exit: Exit
        main_gui_title: Main
        main_item_1: Welcome to Exp_Build x)
        main_item_2: Click on the items to discover all
        main_item_3: the possibilities

        leather_gui_title: Leather
        leather_item: Custom Leather
        leather_helmet: Leather helmet
        leather_chestplate: Leather chestplate
        leather_leggings: Leather leggings
        leather_boots: Leather boots
        red_color: §8RED color
        green_color: §8GREEN color
        blue_color: §8BLUE color
        red: RED§7 'level'
        green: GREEN§7 'level'
        blue: BLUE§7 'level'

        organic_gui_title: Organic generator
        organic_item: Humanoid-Organic-Generator
        pitch_angle_conf: Pitch angle configuration
        yaw_angle_conf: Yaw angle configuration
        click_change_angle: Click for change 'type' angle
        click_enable_disable: Click for enable / disable member
        click_pregen: Click for pregenerate the organic
        click_generate: Click for generate the organic
        click_clear_particle: Click for clear particle
        member_conf: Member configuration
        height: Height
        organic_height: "Organic Height :§7 'value'"
        interact_member: Right Click, Left click or Shift Click
        switch_member: "'type' :§7 'state'"
        pitch_level: "Pitch :§7 'level'"
        yaw_level: "Yaw :§7 'level'"


        flower_gui_title: Flower Brush
        flower_item: Create your flower brush
        brush_enable: §a Enable
        brush_disable: §4 Disable
        radius_text: Radius
        radius_value: "Radius :§7 'value'"
        air_text: Air
        air_value: "Air :§7 'value'"
        total: "Total :§7 'value'"
        right_arrow: ">§7 'value'"
        click_for_change: Click for change percentage
        property_key: "PropertyKey : §7'value'"
        value_propertykey : "Value : §7'value'"
        click_for_change_property: Click for change property






    fr:
      main:
        plugin_enable: Plugin on
        plugin_disable: Plugin off

        listeners_load: Listeners chargé
        commands_load: Commands chargé
        config_load: Config chargé
        gui_load: Gui enregistré
        brush_load: brush enregistré
        schematic_transfert_file: Transfert Schematic file Server'num'.yml create

        checking_update: Check updates...
        not_new_update: Il n'y a pas de nouvelle mise à jour disponible actuellement
        new_update_available: Une nouvelle mise a jour est disponible, vous utilisez la version 'v1' , version 'v2' disponible
        unable_check_update: Inpossible de check les versions disponible 'error'

      brush:
        brush_enable: Brush 'brush' activé
        brush_enable_with_radius: Brush 'brush' activé, rayon = 'radius'
        brush_enable_with_material: Brush 'brush' activé, pattern = 'pattern'
        brush_enable_with_radius_pattern: Brush 'brush' activé, rayon = 'radius', pattern = 'pattern'
        brush_disable: Brush désactivé
        brush_registered: Brush 'brush' enregistré
        material_set: Material défini
        radius_set: Radius défini

        player_registered: Joueur 'player' enregistré
        builder_profile_registered: Profile Builder enregistré
        player_already_registered: Vous êtes déjà enregistré

        point_add: Point ajouté à ('point')
        point_not_save: Taille limite, point non sauvegardé

      permission:
        dont_perm: Vous n'avez pas la permission
        console_not_execute_cmd: La console ne peux pas exécuter cette commande

      selection:
        set_pos_1: Pos 1 défini à ('pos')
        set_pos_1_with_area: Pos 1 défini à ('pos') ('area')
        set_pos_2: Pos 2 défini à ('pos')
        set_pos_2_with_area: Pos 2 défini à ('pos') ('area')
        add_vertex_pos: Vertex ajouté ('pos')
        selection_clear: Selection effacé
        set_selection: Selection 'selection' défini

        block_modified: "'num' blocs ont été modifé"
        block_modified_with_time: "'num' blocs ont été modifé ('num2' blocks/s)"

      error:
        error_region: Erreur région n° 'num' ! 'error'
        error_selection: §4Error ! IncompleteRegionException; Utilisez 'selection' selection et completez votre selection
        error_brushbuilder: §4Error ! 'player' n'eest pas enregistré en tant que Builder, il doit être opérateur ou avoir la permission expertbuild.use
        error_jsch_exception: Error JSch-Exception, voir console
        error_sftp_exception: Error Sftp-Exception, voir console
        file_configuration_error: Le fichier de configuration dans le dossier ExpertBuild est erroné ou corrompu; Réparez le fichier ou supprimez tous les fichier pour que le plugin les re-créer
        incomplete_selection: Selection incomplete; Particule stoppé, ceci est normal
        invalid_number: Format du nombre invalide
        invalid_number_integer: Format du nombre invalide, utilisé un chiffre
        invalid_number_integer_upper_0: Format du nombre invalide, le chiffre doit être suppérieur à 0
        invalid_material: Pattern invalide
        invalid_material_set: Pattern invalide, pattern défini 'pattern'
        invalid_biome: Biome invalide
        invalid_biome_set: Biome invalide, biome défini 'biome'

      tools:
        give_tool: L' 'tool' donné

      commands:
        use: Utilisez 'cmd'
        pregeneration: pré-générer
        generate: Générer

        file_not_exist: Le fichier 'file' n'existe pas
        file_too_large: Le fichier est trop volumineux, Augmentez le parametre de tranfert dans le fichier de configuration
        server_off: Serveur non activé
        unknown_server: Serveur inconnu, ré-essayé avec un nom de server valide
        transfert: Tranfert en cours
        dont_restart: Connection au serveur... svp, ne re-chargé pas ExpertBuild, ne re-démarré pas le serveur
        succes_transfert: Transfer fini, Fichier envoya avec succès Imported-'file' sur le serveur 'server'
        transfert_log: Le fichier 'file' exporté avec succes par 'player' sur le serveur 'server'

      gui:
        back: Retour
        exit: Quitté
        main_gui_title: Menu principal
        main_item_1: Bienvenue sur Exp_Build gui x)
        main_item_2: Click sur les items pour découvrir toutes
        main_item_3: les possibilitées

        leather_gui_title: Leather
        leather_item: Custom Leather
        leather_helmet: Casque en cuir
        leather_chestplate: Tunique en cuir
        leather_leggings: Pantalon en cuir
        leather_boots: Bottes en cuir
        red_color: §8Couleur ROUGE
        green_color: §8Couleur VERT
        blue_color: §8Couleur BLEUE
        red: ROUGE§7 'level'
        green: VERT§7  'level'
        blue: BLEUE§7 'level'

        organic_gui_title: Generateur d'organique
        organic_item: Humanoid-Organic-Generator
        pitch_angle_conf: Pitch angle configuration
        yaw_angle_conf: Yaw angle configuration
        click_change_angle: Clic pour changer l'angle 'type'
        click_enable_disable: Clic pour Activer / Désactiver un membre
        click_pregen: Clic pour pre-generer l'organic
        click_generate: Clic pour generer l'organic
        click_clear_particle: Clic pour supprimer les particules
        member_conf: configuration des membres
        height: Hauteur
        organic_height: "Hauteur organique :§7 'value'"
        interact_member: Clic droit, Clic gauche ou Shift clic
        switch_member: "'type' :§7 'state'"
        pitch_level: "Pitch :§7 'level'"
        yaw_level: "Yaw :§7 'level'"


        flower_gui_title: Brush Fleur
        flower_item: Créer ton brush
        brush_enable: §a Activé
        brush_disable: §4 Désactivé
        radius_text: Rayon
        radius_value: "Rayon :§7 'value'"
        air_text: Air
        air_value: "Air :§7 'value'"
        total: "Total :§7 'value'"
        right_arrow: ">§7 'value'"
        click_for_change: Clic pour changer le pourcentage
        property_key: "PropertyKey :§7 'value'"
        value_propertykey: "Valeur :§7 'value'"
        click_for_change_property: Clic pour changer la propriété